version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Simulating Docker build...
artifacts:
  files:
    - '**/*'
